### ISSUE TITLE
I need a docs to use this tool!

### ISSUE THREAD

**Issue by OurCodeBase** [seiya-dev/terabox-app-js#1]
I need to use this project and I don't have enough knowledge of this type of web scraping. Can you please provide a proper documentation to upload and download files from/to terabox.

**Comment by seiya-git** [comment]
Readme updated

**Comment by seiya-git** [comment]
1. Download function not finished yet, you can use [alist](https://github.com/alist-org/alist) as alternative way to download files
2. Rapid upload means that files can be uploaded instantly without waiting if file was uploaded before to terabox
3. tbhash function create special hash file for using with uploader in rapidupload

**Comment by OurCodeBase** [comment]
Ok I'm contributing to your project. I will write a good  docs for this project.
